
# Variables by categories, project_data6
ID = ["Client_ID", "Nurse_ID"]

CATEGORICAL = ["MomsRE", "HSGED", "INCOME", "MARITAL", 
"CLIENT_ABUSE_TIMES_0_HURT_LAST_Y", "CLIENT_ABUSE_TIMES_0_SLAP_PUSH_P",
"CLIENT_ABUSE_TIMES_0_PUNCH_KICK_", "CLIENT_ABUSE_TIMES_0_BURN_BRUISE",
"CLIENT_ABUSE_TIMES_0_HEAD_PERM_I", "CLIENT_ABUSE_TIMES_0_ABUSE_WEAPO",
"CLIENT_BIO_DAD_0_CONTACT_WITH", "CLIENT_LIVING_0_WITH", "CLIENT_WORKING_0_CURRENTLY_WORKI",
"highest_educ", "educ_currently_enrolled_type",
"SERVICE_USE_0_OTHER1_DESC",
"SERVICE_USE_0_OTHER2_DESC",
"SERVICE_USE_0_OTHER3_DESC",
"SERVICE_USE_0_TANF_CLIENT",
"SERVICE_USE_0_FOODSTAMP_CLIENT",
"SERVICE_USE_0_SOCIAL_SECURITY_CL",
"SERVICE_USE_0_UNEMPLOYMENT_CLIEN",
"SERVICE_USE_0_IPV_CLIENT",
"SERVICE_USE_0_CPS_CHILD",
"SERVICE_USE_0_MENTAL_CLIENT",
"SERVICE_USE_0_SMOKE_CLIENT",
"SERVICE_USE_0_ALCOHOL_ABUSE_CLIE",
"SERVICE_USE_0_DRUG_ABUSE_CLIENT",
"SERVICE_USE_0_MEDICAID_CLIENT",
"SERVICE_USE_0_MEDICAID_CHILD",
"SERVICE_USE_0_SCHIP_CLIENT",
"SERVICE_USE_0_SCHIP_CHILD",
"SERVICE_USE_0_SPECIAL_NEEDS_CHIL",
"SERVICE_USE_0_PCP_CLIENT",
"SERVICE_USE_0_PCP_WELL_CHILD",
"SERVICE_USE_0_DEVELOPMENTAL_DISA",
"SERVICE_USE_0_WIC_CLIENT",
"SERVICE_USE_0_CHILD_CARE_CLIENT",
"SERVICE_USE_0_JOB_TRAINING_CLIEN",
"SERVICE_USE_0_HOUSING_CLIENT",
"SERVICE_USE_0_TRANSPORTATION_CLI",
"SERVICE_USE_0_PREVENT_INJURY_CLI",
"SERVICE_USE_0_BIRTH_EDUC_CLASS_C",
"SERVICE_USE_0_LACTATION_CLIENT",
"SERVICE_USE_0_GED_CLIENT",
"SERVICE_USE_0_HIGHER_EDUC_CLIENT",
"SERVICE_USE_0_CHARITY_CLIENT",
"SERVICE_USE_0_LEGAL_CLIENT",
"SERVICE_USE_0_OTHER1",
"SERVICE_USE_0_OTHER2",
"SERVICE_USE_0_OTHER3",
"SERVICE_USE_0_PRIVATE_INSURANCE_",
"SERVICE_USE_0_PRIVATE_INSURANCE1",
"Highest_Nursing_Degree",
"Highest_Non_Nursing_Degree",
"NurseRE",
"PrimRole",
"SecRole"]

BOOLEAN = ["nicu", "premature", "lbw", 
"SERVICE_USE_0_PRIVATE_INSURANCE1",
"CLIENT_ABUSE_EMOTION_0_PHYSICAL_", "CLIENT_ABUSE_EMOTION_0_PHYSICAL_",
"CLIENT_ABUSE_FORCED_0_SEX", "CLIENT_ABUSE_HIT_0_SLAP_LAST_TIM", 
"CLIENT_ABUSE_AFRAID_0_PARTNER", "educ_currently_enrolled",
"live_with_mother", "live_with_FoC_not_spouse", "live_with_spouse_not_FoC",
"live_with_other_family_members", "live_with_infant_or_child",
"live_with_other_adults", "income_employment",
"income_socialsecurity", "income_disability",
"income_other_public_benefits", "income_other", 
"English", "Spanish",
"disease",
"heart_disease",
"high_blood_pressure",
"diabetes",
"kidney_disease",
"epilepsy",
"sickle_cell_disease",
"chronic_gastrointestinal_disease",
"asthma_chronic_pulmonary",
"chronic_urinary_tract_infection",
"chronic_vaginal_infection_sti",
"genetic_disease_congenital_anomalies",
"mental_health",
"other_diseases",
"nurse_English",
"nurse_hispanic",
"nurse_Spanish",
"nurserace_americanindian_alaskanative",
"nurserace_asian",
"nurserace_black",
"nurserace_nativehawaiian_pacificislander",
"nurserace_white"]
"other_diseases"]

NUMERICAL = ["PREPGKG", "PREPGBMI", "age_intake_years", 
"edd_enrollment_interval_weeks", "gest_weeks_intake"]

TIME = "client_enrollment", "client_dob", "client_edd", "NURSE_0_FIRST_HOME_VISIT_DATE", "EarliestCourse",
"EndDate","HireDate","NURSE_0_BIRTH_YEAR", "NURSE_0_YEAR_COMMHEALTH_EXPERIEN", "NURSE_0_YEAR_MATERNAL_EXPERIENCE",
"NURSE_0_YEAR_NURSING_EXPERIENCE"]

MISSING_COLS_LIST = ["CLIENT_ABUSE_AFRAID_0_PARTNER", "CLIENT_ABUSE_EMOTION_0_PHYSICAL_",
"CLIENT_ABUSE_FORCED_0_SEX", "CLIENT_ABUSE_HIT_0_SLAP_LAST_TIM", "CLIENT_ABUSE_HIT_0_SLAP_PARTNER",
"CLIENT_ABUSE_TIMES_0_ABUSE_WEAPO","CLIENT_ABUSE_TIMES_0_BURN_BRUISE",
"CLIENT_ABUSE_TIMES_0_HEAD_PERM_I","CLIENT_ABUSE_TIMES_0_HURT_LAST_Y",
"CLIENT_ABUSE_TIMES_0_PUNCH_KICK_", "CLIENT_ABUSE_TIMES_0_SLAP_PUSH_P",
"CLIENT_WORKING_0_CURRENTLY_WORKI", "English", "INCOME", "PREPGBMI",
"Spanish", "highest_educ"]